name: Manual Pipeline

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the Manual pipeline'
        required: true
        default: 'master'

permissions: write-all

jobs:
  poc-client:
    uses: ./.github/workflows/reusable.yaml
    secrets: inherit
    with:
        branch: ${{ github.event.inputs.branch }}
