name: POC Reusable Workflow

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

permissions: write-all

jobs:
  poc:
    name: POC
    runs-on: ubuntu-latest
    steps:
      - name: PR check!
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            console.log('input-branch: ${{ inputs.branch }}');
            let branch = github.rest.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: '${{ inputs.branch }}'
            })
            console.log(branch)
            let headSha = branch.data.commit.sha
            
            console.log(await github.rest.checks.create({
              name: 'my-check',
              head_sha: headSha,
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'My POC Check',
                summary: 'Results: 1 2 3'
              },
              owner: context.repo.owner,
              repo: context.repo.repo
            }))