name: POC Reusable Workflow

on:
  workflow_call:

permissions: write-all

jobs:
  poc:
    name: POC
    runs-on: ubuntu-latest
    steps:
      - name: PR check!
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            let headSha = '${{ github.event.pull_request.head.sha }}'
            let mergeCommitSha = '${{ github.sha }}'
            
            console.log(await github.rest.checks.create({
              name: 'my-check',
              head_sha: headSha,
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'My POC Check',
                summary: 'Results: 1 2 3'
              },
              owner: context.repo.owner,
              repo: context.repo.repo
            }))